# Pre-commit hooks configuration
# This file provides comprehensive pre-commit hooks for both code and infrastructure

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Terraform hooks
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.86.0
    hooks:
      # Terraform formatting
      - id: terraform_fmt
        args:
          - --args=-recursive

      # Terraform validation
      - id: terraform_validate
        args:
          - --args=-json

      # Terraform security scanning
      - id: terraform_tflint
        args:
          - --args=--config=__GIT_WORKING_DIR__/.tflint.hcl

      # Terraform security checks
      - id: terraform_tfsec
        args:
          - --args=--config-file=.tfsec.yml

      # Terraform documentation
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md
          - --hook-config=--add-to-existing-file=true
          - --hook-config=--create-file-if-not-exist=true

      # Terraform cost estimation
      - id: terraform_checkov
        args:
          - --args=--framework=terraform
          - --args=--skip-check=CKV_AWS_21
          - --args=--skip-check=CKV_AWS_23

      # Terraform plan validation
      - id: terraform_plan
        args:
          - --args=-detailed-exitcode
          - --args=-out=tfplan

  # Node.js/JavaScript hooks
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0
    hooks:
      - id: eslint
        files: \.(js|jsx|ts|tsx)$
        args: [--fix]
        additional_dependencies:
          - eslint@^8.0.0
          - eslint-config-next@^14.0.0

  # Prettier formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args: [--write]
        types_or: [javascript, jsx, ts, tsx, json, yaml, markdown, css, scss]

  # TypeScript checking
  - repo: https://github.com/pre-commit/mirrors-typescript
    rev: v5.3.3
    hooks:
      - id: typescript
        args: [--noEmit]

  # Commit message linting
  - repo: https://github.com/commitlint/commitlint
    rev: v18.4.3
    hooks:
      - id: commitlint
        stages: [commit-msg]
        args: [--config, .commitlintrc.js]

  # Security scanning
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.lock.json

  # Shell script linting
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
        args: [-e, SC1091]

  # YAML linting
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: [-c=.yamllint.yml]

  # Markdown linting
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint
        args: [--fix]
